### ISSUE TITLE
ElasticSearch起動時に`AccessControlException`が発生する

### ISSUE THREAD

**Issue by sugikeitter** [sugikeitter/elasticsearch-kibana-docker#1]
起動時に以下のエラーが出る
```java
elasticsearch    | 2018-06-24 16:19:14,400 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
elasticsearch    | 	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch    | 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:371)
elasticsearch    | 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1805)
elasticsearch    | 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:318)
elasticsearch    | 	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
elasticsearch    | 	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
elasticsearch    | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
elasticsearch    | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
elasticsearch    | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
elasticsearch    | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
elasticsearch    | 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
elasticsearch    | 	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
elasticsearch    | 	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
elasticsearch    | 	at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:171)
elasticsearch    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:140)
elasticsearch    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:119)
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:294)
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136)
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127)
elasticsearch    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
elasticsearch    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
elasticsearch    | 	at org.elasticsearch.cli.Command.main(Command.java:90)
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86)
elasticsearch    |
elasticsearch    | 2018-06-24 16:19:14,580 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
elasticsearch    | 	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch    | 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:371)
elasticsearch    | 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1805)
elasticsearch    | 	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:318)
elasticsearch    | 	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
elasticsearch    | 	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
elasticsearch    | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
elasticsearch    | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
elasticsearch    | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
elasticsearch    | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
elasticsearch    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:163)
elasticsearch    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:119)
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:294)
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136)
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127)
elasticsearch    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
elasticsearch    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
elasticsearch    | 	at org.elasticsearch.cli.Command.main(Command.java:90)
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86)
```

**Comment by sugikeitter** [comment]
https://github.com/elastic/elasticsearch-docker/issues/37 にあるように、
https://github.com/sugikeitter/elasticsearch-kibana-docker/blob/96ba20c4bdce0e64ae6662e6c59116cebb7dfa3f/docker-compose.yml#L15
の部分でデフォルト設定される`/usr/share/elasticsearch/config`を上書きしてしまっている

**Comment by sugikeitter** [comment]
対応完了
https://github.com/sugikeitter/elasticsearch-kibana-docker/commit/d1de9006ebc16fb72bf616ec1ed2fab6f3fa842a
